### ISSUE TITLE
http content headers question

### ISSUE THREAD

**Issue by kmc059000** [pmhsfelix/WebApi.Explorations.ServiceBusRelayHost#2]
Can you explain why these[1] headers are ignored, but added back in[2] if there is a body? What is the reasoning and what possible effects does it have?

Thanks!

[1] https://github.com/pmhsfelix/WebApi.Explorations.ServiceBusRelayHost/blob/master/src/ServiceBusRelayHost/DispatcherService.cs#L31

[2] https://github.com/pmhsfelix/WebApi.Explorations.ServiceBusRelayHost/blob/master/src/ServiceBusRelayHost/DispatcherService.cs#L108

**Comment by pmhsfelix** [comment]
In ASP.NET Web API, headers are divided between request headers, body headers and response headers. These three header types are stored in different locations. For instance, request headers are stored in the `HttpRequestMessage.Headers`, while body headers are stored in `HttpContent.Headers`. However, in WCF they are all stored in the same collection. Due to that, there are two header copying cycles: the first one copies only the request headers (ignoring body headers); the second one copies only the body headers.
Are you having any problem with this?

**Comment by kmc059000** [comment]
No problems, I didn't understand and was looking for clarification. Thank you!
